#!/usr/bin/env python3
"""Attribution for the training corpus.

CREDITS.md (hand-written, next to this file) carries the per-bundle licence
statements, links and thank-yous.  This module generates the per-asset list
from the fetch manifest -- every image, its source page and its authors --
which CC0 does not require but which costs nothing to give.

    python -m unditherer.credits                 # shipped manifest -> unditherer/corpus/ATTRIBUTION.md
    python -m unditherer.credits --manifest <corpus>/manifest.json   # a fetched corpus
"""
import argparse
import json
from collections import Counter, defaultdict
from pathlib import Path

from .paths import CORPUS, SHIPPED_MANIFEST, data_root

SOURCES = {
    "ambientCG": {
        "title": "ambientCG",
        "site": "https://ambientcg.com",
        "licence": "CC0 1.0 Universal",
        "licence_url": "https://docs.ambientcg.com/license/",
        "credit_line": "Created using assets from ambientCG.com, licensed under the Creative Commons CC0 1.0 Universal License.",
    },
    "Poly Haven": {
        "title": "Poly Haven",
        "site": "https://polyhaven.com",
        "licence": "CC0 1.0 Universal",
        "licence_url": "https://polyhaven.com/license",
        "api_terms": "https://github.com/Poly-Haven/Public-API/blob/master/ToS.md",
        "credit_line": "Powered by Poly Haven (https://polyhaven.com) -- textures CC0, fetched through the public API.",
    },
    "OpenGameArt": {
        "title": "Screaming Brain Studios -- Tiny Texture Packs 1-3 (OpenGameArt)",
        "site": "https://opengameart.org/content/tiny-texture-pack",
        "licence": "CC0 1.0 Universal",
        "licence_url": "https://opengameart.org/content/tiny-texture-pack",
        "credit_line": "Tiny Texture Packs 1-3 by Screaming Brain Studios (OpenGameArt, CC0).",
    },
}


def summarise(manifest):
    """Per-source counts, bytes and author tallies."""
    out = {}
    for m in manifest:
        s = out.setdefault(m["source"], {"images": 0, "bytes": 0, "authors": Counter(), "licences": Counter()})
        s["images"] += 1
        s["bytes"] += int(m.get("bytes", 0))
        s["licences"][m.get("licence", "?")] += 1
        for a in m.get("authors") or []:
            s["authors"][a] += 1
    return out


def attribution_markdown(manifest):
    summary = summarise(manifest)
    lines = ["# Training corpus attribution", "",
             "Generated by `python -m unditherer.credits` from the fetch manifest. Every asset is",
             "CC0 1.0 Universal (no attribution required); this list exists so that the people",
             "who made the material are named anyway. Bundle-level statements, links and",
             "thank-yous are in `unditherer/CREDITS.md`.", ""]
    for source, meta in SOURCES.items():
        s = summary.get(source)
        if not s:
            continue
        lines += [f"## {meta['title']}", "",
                  f"- Site: <{meta['site']}>",
                  f"- Licence: {meta['licence']} -- <{meta['licence_url']}>",
                  f"- Images used: {s['images']} ({s['bytes'] / 1e6:.0f} MB)"]
        if s["authors"]:
            lines.append("- Authors: " + ", ".join(f"{a} ({n})" for a, n in s["authors"].most_common()))
        lines += ["", "| Asset | Page | Authors |", "|---|---|---|"]
        for m in sorted((m for m in manifest if m["source"] == source), key=lambda m: m["id"]):
            aid = Path(m["id"].split(":")[-1]).name if source == "OpenGameArt" else m["id"]
            lines.append(f"| {aid} | <{m['url']}> | {', '.join(m.get('authors') or [])} |")
        lines.append("")
    return "\n".join(lines)


def write_attribution(manifest_path, out_path):
    manifest = json.loads(Path(manifest_path).read_text())
    out_path = Path(out_path)
    out_path.write_text(attribution_markdown(manifest))
    return out_path


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--manifest", default=None, help=f"default {SHIPPED_MANIFEST}")
    ap.add_argument("--out", default=None, help="default: ATTRIBUTION.md next to the manifest")
    args = ap.parse_args(argv)
    mpath = Path(args.manifest) if args.manifest else SHIPPED_MANIFEST
    if not mpath.exists():
        raise SystemExit(f"no manifest at {mpath}")
    out = Path(args.out) if args.out else mpath.parent / "ATTRIBUTION.md"
    manifest = json.loads(mpath.read_text())
    for source, s in summarise(manifest).items():
        print(f"{source:12} {s['images']:5d} images  {s['bytes'] / 1e6:6.0f} MB  licences {dict(s['licences'])}"
              + (f"  authors {len(s['authors'])}" if s["authors"] else ""))
    print(f"-> {write_attribution(mpath, out)}")


if __name__ == "__main__":
    main()
