#!/usr/bin/env python3
"""Regenerate tools/tamem_ghidra.h from vendor/TADR/src/DDraw/tamem.h.

Transforms applied so Ghidra's CParser (C, not C++) can digest it:
  - the three #include lines are dropped; a stub prelude supplies the Windows/
    DirectX typedefs actually used (pointer-sized handles, POINT/RECT/WNDCLASS,
    DDSURFACEDESC as an opaque 108-byte block)
  - static_assert lines stripped (layouts are asserted upstream in TADR builds)
  - C-illegal forward enum declarations stripped
  - bool -> unsigned char (matches MSVC's 1-byte bool under #pragma pack(1))
  - "enum class" -> plain enum
  - the three trailing "namespace X { enum ... }" wrappers are unwrapped to
    bare enums (nothing else in the file references them by scope)
"""
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]   # the repository root
SRC = ROOT / "vendor/TADR/src/DDraw/tamem.h"
DST = ROOT / "tools/tamem_ghidra.h"

PRELUDE = """/* tamem_ghidra.h -- self-contained trim of vendor/TADR/src/DDraw/tamem.h
 * for Ghidra's CParser. Generated by tools/make_tamem_ghidra.py -- edit that,
 * not this. Struct layouts are #pragma pack(1) and offset-checked upstream. */
typedef unsigned char BYTE;
typedef unsigned short WORD;
typedef unsigned long DWORD;
typedef int BOOL;
typedef long LONG;
typedef unsigned int UINT;
typedef short __int16;
typedef void *LPVOID;
typedef BYTE *LPBYTE;
typedef void *HWND;
typedef void *HANDLE;
typedef void *LPDIRECTSOUND;
typedef void *LPDIRECTSOUNDBUFFER;
typedef struct tagPOINT { LONG x; LONG y; } POINT;
typedef struct tagRECT { LONG left; LONG top; LONG right; LONG bottom; } RECT;
typedef struct tagWNDCLASS {  /* 32-bit WNDCLASSA, 40 bytes */
    UINT style;
    void *lpfnWndProc;
    int cbClsExtra;
    int cbWndExtra;
    void *hInstance;
    void *hIcon;
    void *hCursor;
    void *hbrBackground;
    char *lpszMenuName;
    char *lpszClassName;
} WNDCLASS;
typedef struct _DDSURFACEDESC {  /* opaque: 32-bit ddraw.h size 0x6C */
    DWORD opaque[27];
} DDSURFACEDESC;
"""


def main():
    text = SRC.read_text(errors="replace")
    # unwrap "namespace X\n{\n <enum ...>;\n};?" -> the enum alone
    text = re.sub(r"namespace\s+\w+\s*\r?\n\{(.*?\n\s*\};?)\r?\n\};?",
                  r"\1", text, flags=re.S)
    out = []
    for line in text.splitlines():
        ls = line.strip()
        if ls.startswith("#include") or ls.startswith("static_assert"):
            continue
        if re.fullmatch(r"enum \w+;", ls):
            continue
        line = re.sub(r"\bbool\b", "unsigned char", line)
        line = re.sub(r"\benum\s+class\b", "enum", line)
        out.append(line)
    DST.write_text(PRELUDE + "\n".join(out) + "\n")
    print(f"wrote {DST} ({len(out)} lines + prelude)")


if __name__ == "__main__":
    main()
